/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import javax.swing.ImageIcon;

/**
 *
 * @author Tijex
 */
public class ayuda extends javax.swing.JFrame {

    /**
     * Creates new form ayuda
     */
    public ayuda() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/DevHuvbn.png")).getImage());
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        
        Sigder2.setVisible(false);
        Sigder3.setVisible(false);
        Sigder4.setVisible(false);
        Sigder5.setVisible(false);
        Sigder6.setVisible(false);
        Sigder7.setVisible(false);
        Sigder8.setVisible(false);
        Sigder9.setVisible(false);
        Sigder10.setVisible(false);
        Sigder11.setVisible(false);
        Sigder12.setVisible(false);
        Sigder13.setVisible(false);
        Sigder14.setVisible(false);
        Sigder15.setVisible(false);
        Sigder16.setVisible(false);
        Sigder17.setVisible(false);
        Sigder18.setVisible(false);
        Sigder19.setVisible(false);
        Sigder20.setVisible(false);
        Sigder21.setVisible(false);
        
        Sigizq1.setVisible(false);
        Sigizq2.setVisible(false);
        Sigizq3.setVisible(false);
        Sigizq4.setVisible(false);
        Sigizq5.setVisible(false);
        Sigizq6.setVisible(false);
        Sigizq7.setVisible(false);
        Sigizq8.setVisible(false);
        Sigizq9.setVisible(false);
        Sigizq10.setVisible(false);
        Sigizq11.setVisible(false);
        Sigizq12.setVisible(false);
        Sigizq13.setVisible(false);
        Sigizq14.setVisible(false);
        Sigizq15.setVisible(false);
        Sigizq16.setVisible(false);
        Sigizq17.setVisible(false);
        Sigizq18.setVisible(false);
        Sigizq19.setVisible(false);
        Sigizq20.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Barra1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Sigizq20 = new javax.swing.JLabel();
        Sigizq19 = new javax.swing.JLabel();
        Sigizq18 = new javax.swing.JLabel();
        Sigizq17 = new javax.swing.JLabel();
        Sigizq16 = new javax.swing.JLabel();
        Sigizq15 = new javax.swing.JLabel();
        Sigizq14 = new javax.swing.JLabel();
        Sigizq13 = new javax.swing.JLabel();
        Sigizq12 = new javax.swing.JLabel();
        Sigizq11 = new javax.swing.JLabel();
        Sigizq10 = new javax.swing.JLabel();
        Sigizq9 = new javax.swing.JLabel();
        Sigizq8 = new javax.swing.JLabel();
        Sigizq7 = new javax.swing.JLabel();
        Sigizq6 = new javax.swing.JLabel();
        Sigizq5 = new javax.swing.JLabel();
        Sigizq4 = new javax.swing.JLabel();
        Sigizq3 = new javax.swing.JLabel();
        Sigizq2 = new javax.swing.JLabel();
        Sigizq1 = new javax.swing.JLabel();
        Sigder20 = new javax.swing.JLabel();
        Sigder19 = new javax.swing.JLabel();
        Sigder18 = new javax.swing.JLabel();
        Sigder17 = new javax.swing.JLabel();
        Sigder16 = new javax.swing.JLabel();
        Sigder21 = new javax.swing.JLabel();
        Sigder15 = new javax.swing.JLabel();
        Sigder14 = new javax.swing.JLabel();
        Sigder13 = new javax.swing.JLabel();
        Sigder11 = new javax.swing.JLabel();
        Sigder12 = new javax.swing.JLabel();
        Sigder10 = new javax.swing.JLabel();
        Sigder9 = new javax.swing.JLabel();
        Sigder8 = new javax.swing.JLabel();
        Sigder7 = new javax.swing.JLabel();
        Sigder6 = new javax.swing.JLabel();
        Sigder5 = new javax.swing.JLabel();
        Sigder4 = new javax.swing.JLabel();
        Sigder3 = new javax.swing.JLabel();
        Sigder2 = new javax.swing.JLabel();
        Sigder1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra1.setBackground(new java.awt.Color(246, 246, 246));

        jLabel21.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Proyecto Final- Programacion II - Ingenieria Industrial - Profesor Jorge Luis Escobar");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/v2icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1devhub.png"))); // NOI18N

        javax.swing.GroupLayout Barra1Layout = new javax.swing.GroupLayout(Barra1);
        Barra1.setLayout(Barra1Layout);
        Barra1Layout.setHorizontalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(7, 7, 7))
        );
        Barra1Layout.setVerticalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra1Layout.createSequentialGroup()
                .addGroup(Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Barra1Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));

        Sigizq20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq20MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq19MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq18MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq17MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq16MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq15MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq14MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq13MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq12MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq11MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq10MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq9MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq8MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq7MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq6MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq5MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq4MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq3MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq2MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigizq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        Sigizq1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigizq1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigizq1MouseClicked(evt);
            }
        });
        jPanel1.add(Sigizq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        Sigder20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        Sigder20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder20MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder20, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder19MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder19, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder18MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder17MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder16MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder21MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder21, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder15MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder14MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder13MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder11MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder12MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder10MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder9MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder8MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder7MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder6MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder5MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder4MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder3MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder2MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        Sigder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sig1.png"))); // NOI18N
        Sigder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sigder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sigder1MouseClicked(evt);
            }
        });
        jPanel1.add(Sigder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto17v2.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto16.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto15B.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto15.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto14.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto13.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto12.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto11.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto10.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto9.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto8v1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto7.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto6B.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto6.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto5.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto4.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto3.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto0.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tuto1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sigder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder1MouseClicked
        jLabel1.setVisible(false);
        jLabel2.setVisible(true);
        Sigder1.setVisible(false);
        Sigder2.setVisible(true);
        Sigizq2.setVisible(true);
    }//GEN-LAST:event_Sigder1MouseClicked

    private void Sigder2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder2MouseClicked
        jLabel2.setVisible(false);
        jLabel3.setVisible(true);
        Sigder2.setVisible(false);
        Sigder3.setVisible(true);
        Sigizq2.setVisible(false);
        Sigizq3.setVisible(true);
    }//GEN-LAST:event_Sigder2MouseClicked

    private void Sigder3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder3MouseClicked
        jLabel3.setVisible(false);
        jLabel4.setVisible(true);
        Sigder3.setVisible(false);
        Sigder4.setVisible(true);
        Sigizq3.setVisible(false);
        Sigizq4.setVisible(true);
    }//GEN-LAST:event_Sigder3MouseClicked

    private void Sigder4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder4MouseClicked
        jLabel4.setVisible(false);
        jLabel5.setVisible(true);
        Sigder4.setVisible(false);
        Sigder5.setVisible(true);
        Sigizq4.setVisible(false);
        Sigizq5.setVisible(true);
    }//GEN-LAST:event_Sigder4MouseClicked

    private void Sigder5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder5MouseClicked
        jLabel5.setVisible(false);
        jLabel6.setVisible(true);
        Sigder5.setVisible(false);
        Sigder6.setVisible(true);
        Sigizq5.setVisible(false);
        Sigizq6.setVisible(true);
    }//GEN-LAST:event_Sigder5MouseClicked

    private void Sigder6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder6MouseClicked
        jLabel6.setVisible(false);
        jLabel7.setVisible(true);
        Sigder6.setVisible(false);
        Sigder7.setVisible(true);
        Sigizq6.setVisible(false);
        Sigizq7.setVisible(true);
    }//GEN-LAST:event_Sigder6MouseClicked

    private void Sigder7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder7MouseClicked
        jLabel7.setVisible(false);
        jLabel8.setVisible(true);
        Sigder7.setVisible(false);
        Sigder8.setVisible(true);
        Sigizq7.setVisible(false);
        Sigizq8.setVisible(true);
    }//GEN-LAST:event_Sigder7MouseClicked

    private void Sigder8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder8MouseClicked
        jLabel8.setVisible(false);
        jLabel9.setVisible(true);
        Sigder8.setVisible(false);
        Sigder9.setVisible(true);
        Sigizq8.setVisible(false);
        Sigizq9.setVisible(true);
    }//GEN-LAST:event_Sigder8MouseClicked

    private void Sigder9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder9MouseClicked
        jLabel9.setVisible(false);
        jLabel10.setVisible(true);
        Sigder9.setVisible(false);
        Sigder10.setVisible(true);
        Sigizq9.setVisible(false);
        Sigizq10.setVisible(true);
    }//GEN-LAST:event_Sigder9MouseClicked

    private void Sigder10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder10MouseClicked
        jLabel10.setVisible(false);
        jLabel11.setVisible(true);
        Sigder10.setVisible(false);
        Sigder11.setVisible(true);
        Sigizq10.setVisible(false);
        Sigizq11.setVisible(true);
    }//GEN-LAST:event_Sigder10MouseClicked

    private void Sigder11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder11MouseClicked
        jLabel11.setVisible(false);
        jLabel12.setVisible(true);
        Sigder11.setVisible(false);
        Sigder12.setVisible(true);
        Sigizq11.setVisible(false);
        Sigizq12.setVisible(true);
    }//GEN-LAST:event_Sigder11MouseClicked

    private void Sigder12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder12MouseClicked
        jLabel12.setVisible(false);
        jLabel13.setVisible(true);
        Sigder12.setVisible(false);
        Sigder13.setVisible(true);
        Sigizq12.setVisible(false);
        Sigizq13.setVisible(true);
    }//GEN-LAST:event_Sigder12MouseClicked

    private void Sigder13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder13MouseClicked
        jLabel13.setVisible(false);
        jLabel14.setVisible(true);
        Sigder13.setVisible(false);
        Sigder14.setVisible(true);
        Sigizq13.setVisible(false);
        Sigizq14.setVisible(true);
    }//GEN-LAST:event_Sigder13MouseClicked

    private void Sigder14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder14MouseClicked
        jLabel14.setVisible(false);
        jLabel15.setVisible(true);
        Sigder14.setVisible(false);
        Sigder15.setVisible(true);
        Sigizq14.setVisible(false);
        Sigizq15.setVisible(true);
    }//GEN-LAST:event_Sigder14MouseClicked

    private void Sigder15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder15MouseClicked
        jLabel15.setVisible(false);
        jLabel16.setVisible(true);
        Sigder15.setVisible(false);
        Sigder16.setVisible(true);
        Sigizq15.setVisible(false);
        Sigizq16.setVisible(true);
    }//GEN-LAST:event_Sigder15MouseClicked

    private void Sigder16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder16MouseClicked
        jLabel16.setVisible(false);
        jLabel17.setVisible(true);
        Sigder16.setVisible(false);
        Sigder17.setVisible(true);
        Sigizq16.setVisible(false);
        Sigizq17.setVisible(true);
    }//GEN-LAST:event_Sigder16MouseClicked

    private void Sigder17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder17MouseClicked
        jLabel17.setVisible(false);
        jLabel18.setVisible(true);
        Sigder17.setVisible(false);
        Sigder18.setVisible(true);
        Sigizq17.setVisible(false);
        Sigizq18.setVisible(true);
    }//GEN-LAST:event_Sigder17MouseClicked

    private void Sigder18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder18MouseClicked
        jLabel18.setVisible(false);
        jLabel19.setVisible(true);
        Sigder18.setVisible(false);
        Sigder19.setVisible(true);
        Sigizq18.setVisible(false);
        Sigizq19.setVisible(true);
    }//GEN-LAST:event_Sigder18MouseClicked

    private void Sigder19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder19MouseClicked
        jLabel19.setVisible(false);
        jLabel20.setVisible(true);
        Sigder19.setVisible(false);
        Sigder20.setVisible(true);
        Sigizq19.setVisible(false);
        Sigizq20.setVisible(true);
    }//GEN-LAST:event_Sigder19MouseClicked

    private void Sigder20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder20MouseClicked
        this.dispose();
    }//GEN-LAST:event_Sigder20MouseClicked

    private void Sigder21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigder21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Sigder21MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void Sigizq1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Sigizq1MouseClicked

    private void Sigizq2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq2MouseClicked
        Sigizq2.setVisible(false);
        jLabel2.setVisible(false);
        jLabel1.setVisible(true);
        Sigder2.setVisible(false);
        Sigder1.setVisible(true);
    }//GEN-LAST:event_Sigizq2MouseClicked

    private void Sigizq3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq3MouseClicked
        Sigizq3.setVisible(false);
        Sigizq2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel2.setVisible(true);
        Sigder3.setVisible(false);
        Sigder2.setVisible(true);
    }//GEN-LAST:event_Sigizq3MouseClicked

    private void Sigizq4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq4MouseClicked
        Sigizq4.setVisible(false);
        Sigizq3.setVisible(true);
        jLabel4.setVisible(false);
        jLabel3.setVisible(true);
        Sigder4.setVisible(false);
        Sigder3.setVisible(true);
        
    }//GEN-LAST:event_Sigizq4MouseClicked

    private void Sigizq5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq5MouseClicked
        Sigizq5.setVisible(false);
        Sigizq4.setVisible(true);
        jLabel5.setVisible(false);
        jLabel4.setVisible(true);
        Sigder5.setVisible(false);
        Sigder4.setVisible(true);
    }//GEN-LAST:event_Sigizq5MouseClicked

    private void Sigizq6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq6MouseClicked
        Sigizq6.setVisible(false);
        Sigizq5.setVisible(true);
        jLabel6.setVisible(false);
        jLabel5.setVisible(true);
        Sigder6.setVisible(false);
        Sigder5.setVisible(true);
    }//GEN-LAST:event_Sigizq6MouseClicked

    private void Sigizq7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq7MouseClicked
        Sigizq7.setVisible(false);
        Sigizq6.setVisible(true);
        jLabel7.setVisible(false);
        jLabel6.setVisible(true);
        Sigder7.setVisible(false);
        Sigder6.setVisible(true);
    }//GEN-LAST:event_Sigizq7MouseClicked

    private void Sigizq8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq8MouseClicked
        Sigizq8.setVisible(false);
        Sigizq7.setVisible(true);
        jLabel8.setVisible(false);
        jLabel7.setVisible(true);
        Sigder8.setVisible(false);
        Sigder7.setVisible(true);
    }//GEN-LAST:event_Sigizq8MouseClicked

    private void Sigizq9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq9MouseClicked
        Sigizq9.setVisible(false);
        Sigizq8.setVisible(true);
        jLabel9.setVisible(false);
        jLabel8.setVisible(true);
        Sigder9.setVisible(false);
        Sigder8.setVisible(true);
    }//GEN-LAST:event_Sigizq9MouseClicked

    private void Sigizq10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq10MouseClicked
        Sigizq10.setVisible(false);
        Sigizq9.setVisible(true);
        jLabel10.setVisible(false);
        jLabel9.setVisible(true);
        Sigder10.setVisible(false);
        Sigder9.setVisible(true);
    }//GEN-LAST:event_Sigizq10MouseClicked

    private void Sigizq11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq11MouseClicked
        Sigizq11.setVisible(false);
        Sigizq10.setVisible(true);
        jLabel11.setVisible(false);
        jLabel10.setVisible(true);
        Sigder11.setVisible(false);
        Sigder10.setVisible(true);
    }//GEN-LAST:event_Sigizq11MouseClicked

    private void Sigizq12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq12MouseClicked
        Sigizq12.setVisible(false);
        Sigizq11.setVisible(true);
        jLabel12.setVisible(false);
        jLabel11.setVisible(true);
        Sigder12.setVisible(false);
        Sigder11.setVisible(true);
    }//GEN-LAST:event_Sigizq12MouseClicked

    private void Sigizq13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq13MouseClicked
        Sigizq13.setVisible(false);
        Sigizq12.setVisible(true);
        jLabel13.setVisible(false);
        jLabel12.setVisible(true);
        Sigder13.setVisible(false);
        Sigder12.setVisible(true);
    }//GEN-LAST:event_Sigizq13MouseClicked

    private void Sigizq14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq14MouseClicked
        Sigizq14.setVisible(false);
        Sigizq13.setVisible(true);
        jLabel14.setVisible(false);
        jLabel13.setVisible(true);
        Sigder14.setVisible(false);
        Sigder13.setVisible(true);
    }//GEN-LAST:event_Sigizq14MouseClicked

    private void Sigizq15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq15MouseClicked
        Sigizq15.setVisible(false);
        Sigizq14.setVisible(true);
        jLabel15.setVisible(false);
        jLabel14.setVisible(true);
        Sigder15.setVisible(false);
        Sigder14.setVisible(true);
    }//GEN-LAST:event_Sigizq15MouseClicked

    private void Sigizq16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq16MouseClicked
        Sigizq16.setVisible(false);
        Sigizq15.setVisible(true);
        jLabel16.setVisible(false);
        jLabel15.setVisible(true);
        Sigder16.setVisible(false);
        Sigder15.setVisible(true);
    }//GEN-LAST:event_Sigizq16MouseClicked

    private void Sigizq17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq17MouseClicked
        Sigizq17.setVisible(false);
        Sigizq16.setVisible(true);
        jLabel17.setVisible(false);
        jLabel16.setVisible(true);
        Sigder17.setVisible(false);
        Sigder16.setVisible(true);
    }//GEN-LAST:event_Sigizq17MouseClicked

    private void Sigizq18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq18MouseClicked
        Sigizq18.setVisible(false);
        Sigizq17.setVisible(true);
        jLabel18.setVisible(false);
        jLabel17.setVisible(true);
        Sigder18.setVisible(false);
        Sigder17.setVisible(true);
    }//GEN-LAST:event_Sigizq18MouseClicked

    private void Sigizq19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq19MouseClicked
        Sigizq19.setVisible(false);
        Sigizq18.setVisible(true);
        jLabel19.setVisible(false);
        jLabel18.setVisible(true);
        Sigder19.setVisible(false);
        Sigder18.setVisible(true);
    }//GEN-LAST:event_Sigizq19MouseClicked

    private void Sigizq20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sigizq20MouseClicked
        Sigizq20.setVisible(false);
        Sigizq19.setVisible(true);
        jLabel20.setVisible(false);
        jLabel19.setVisible(true);
        Sigder20.setVisible(false);
        Sigder19.setVisible(true);
    }//GEN-LAST:event_Sigizq20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ayuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra1;
    private javax.swing.JLabel Sigder1;
    private javax.swing.JLabel Sigder10;
    private javax.swing.JLabel Sigder11;
    private javax.swing.JLabel Sigder12;
    private javax.swing.JLabel Sigder13;
    private javax.swing.JLabel Sigder14;
    private javax.swing.JLabel Sigder15;
    private javax.swing.JLabel Sigder16;
    private javax.swing.JLabel Sigder17;
    private javax.swing.JLabel Sigder18;
    private javax.swing.JLabel Sigder19;
    private javax.swing.JLabel Sigder2;
    private javax.swing.JLabel Sigder20;
    private javax.swing.JLabel Sigder21;
    private javax.swing.JLabel Sigder3;
    private javax.swing.JLabel Sigder4;
    private javax.swing.JLabel Sigder5;
    private javax.swing.JLabel Sigder6;
    private javax.swing.JLabel Sigder7;
    private javax.swing.JLabel Sigder8;
    private javax.swing.JLabel Sigder9;
    private javax.swing.JLabel Sigizq1;
    private javax.swing.JLabel Sigizq10;
    private javax.swing.JLabel Sigizq11;
    private javax.swing.JLabel Sigizq12;
    private javax.swing.JLabel Sigizq13;
    private javax.swing.JLabel Sigizq14;
    private javax.swing.JLabel Sigizq15;
    private javax.swing.JLabel Sigizq16;
    private javax.swing.JLabel Sigizq17;
    private javax.swing.JLabel Sigizq18;
    private javax.swing.JLabel Sigizq19;
    private javax.swing.JLabel Sigizq2;
    private javax.swing.JLabel Sigizq20;
    private javax.swing.JLabel Sigizq3;
    private javax.swing.JLabel Sigizq4;
    private javax.swing.JLabel Sigizq5;
    private javax.swing.JLabel Sigizq6;
    private javax.swing.JLabel Sigizq7;
    private javax.swing.JLabel Sigizq8;
    private javax.swing.JLabel Sigizq9;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
