/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class calculadora extends javax.swing.JFrame {

   int num1,num2;
   String signo;
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/DevHuvbn.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ac = new javax.swing.JButton();
        div = new javax.swing.JButton();
        el = new javax.swing.JButton();
        punt = new javax.swing.JButton();
        entr = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        ig = new javax.swing.JButton();
        por = new javax.swing.JButton();
        rest = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtOperacion = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Barra1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/AC.png"))); // NOI18N
        ac.setBorder(null);
        ac.setBorderPainted(false);
        ac.setContentAreaFilled(false);
        ac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ac.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2AC.png"))); // NOI18N
        ac.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2AC.png"))); // NOI18N
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        jPanel1.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        div.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/dividir1.png"))); // NOI18N
        div.setBorder(null);
        div.setBorderPainted(false);
        div.setContentAreaFilled(false);
        div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        div.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/dividir2.png"))); // NOI18N
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        jPanel1.add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        el.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/1elevado.png"))); // NOI18N
        el.setBorder(null);
        el.setBorderPainted(false);
        el.setContentAreaFilled(false);
        el.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        el.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2elevado.png"))); // NOI18N
        el.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2elevado.png"))); // NOI18N
        el.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elActionPerformed(evt);
            }
        });
        jPanel1.add(el, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        punt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/punto1.png"))); // NOI18N
        punt.setBorder(null);
        punt.setBorderPainted(false);
        punt.setContentAreaFilled(false);
        punt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        punt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/punto2.png"))); // NOI18N
        punt.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/punto2.png"))); // NOI18N
        punt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntActionPerformed(evt);
            }
        });
        jPanel1.add(punt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        entr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/1porciento.png"))); // NOI18N
        entr.setBorder(null);
        entr.setBorderPainted(false);
        entr.setContentAreaFilled(false);
        entr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entr.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2porciento.png"))); // NOI18N
        entr.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2elevado.png"))); // NOI18N
        entr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrActionPerformed(evt);
            }
        });
        jPanel1.add(entr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        n9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/9a.png"))); // NOI18N
        n9.setBorder(null);
        n9.setBorderPainted(false);
        n9.setContentAreaFilled(false);
        n9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/9b.png"))); // NOI18N
        n9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/9b.png"))); // NOI18N
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        jPanel1.add(n9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        n6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/6a.png"))); // NOI18N
        n6.setBorder(null);
        n6.setBorderPainted(false);
        n6.setContentAreaFilled(false);
        n6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/6b.png"))); // NOI18N
        n6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/6b.png"))); // NOI18N
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });
        jPanel1.add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        n3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/3a.png"))); // NOI18N
        n3.setBorder(null);
        n3.setBorderPainted(false);
        n3.setContentAreaFilled(false);
        n3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/3b.png"))); // NOI18N
        n3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/3b.png"))); // NOI18N
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        jPanel1.add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        ig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/igual1.png"))); // NOI18N
        ig.setBorder(null);
        ig.setBorderPainted(false);
        ig.setContentAreaFilled(false);
        ig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ig.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/igual2.png"))); // NOI18N
        ig.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/igual2.png"))); // NOI18N
        ig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igActionPerformed(evt);
            }
        });
        jPanel1.add(ig, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        por.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/multiplicacion1.png"))); // NOI18N
        por.setBorder(null);
        por.setBorderPainted(false);
        por.setContentAreaFilled(false);
        por.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        por.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/multiplicacion2.png"))); // NOI18N
        por.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/multiplicacion2.png"))); // NOI18N
        por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porActionPerformed(evt);
            }
        });
        jPanel1.add(por, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        rest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/resta1.png"))); // NOI18N
        rest.setBorder(null);
        rest.setBorderPainted(false);
        rest.setContentAreaFilled(false);
        rest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rest.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/resta2.png"))); // NOI18N
        rest.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/resta2.png"))); // NOI18N
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });
        jPanel1.add(rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        sum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/suma1.png"))); // NOI18N
        sum.setBorder(null);
        sum.setBorderPainted(false);
        sum.setContentAreaFilled(false);
        sum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sum.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/suma2.png"))); // NOI18N
        sum.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/suma2.png"))); // NOI18N
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        jPanel1.add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, -1));

        n7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/7a.png"))); // NOI18N
        n7.setBorder(null);
        n7.setBorderPainted(false);
        n7.setContentAreaFilled(false);
        n7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/7b.png"))); // NOI18N
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });
        jPanel1.add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        n4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/4a.png"))); // NOI18N
        n4.setBorder(null);
        n4.setBorderPainted(false);
        n4.setContentAreaFilled(false);
        n4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/4b.png"))); // NOI18N
        n4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/4b.png"))); // NOI18N
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });
        jPanel1.add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        n0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/00.png"))); // NOI18N
        n0.setBorder(null);
        n0.setBorderPainted(false);
        n0.setContentAreaFilled(false);
        n0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/000.png"))); // NOI18N
        n0.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/000.png"))); // NOI18N
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        jPanel1.add(n0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 160, -1));

        n8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/8a.png"))); // NOI18N
        n8.setBorder(null);
        n8.setBorderPainted(false);
        n8.setContentAreaFilled(false);
        n8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/8b.png"))); // NOI18N
        n8.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/8b.png"))); // NOI18N
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });
        jPanel1.add(n8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        n5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/5a.png"))); // NOI18N
        n5.setBorder(null);
        n5.setBorderPainted(false);
        n5.setContentAreaFilled(false);
        n5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/5b.png"))); // NOI18N
        n5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/5b.png"))); // NOI18N
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });
        jPanel1.add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        n2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2a.png"))); // NOI18N
        n2.setBorder(null);
        n2.setBorderPainted(false);
        n2.setContentAreaFilled(false);
        n2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/2b.png"))); // NOI18N
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        jPanel1.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        n1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/1a.png"))); // NOI18N
        n1.setBorder(null);
        n1.setBorderPainted(false);
        n1.setContentAreaFilled(false);
        n1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        n1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/1b.png"))); // NOI18N
        n1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculada/1b.png"))); // NOI18N
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        jPanel1.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOperacion.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(102, 102, 102));
        txtOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 20));

        txtResultado.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtResultado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 50));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 184, -1));

        Barra1.setBackground(new java.awt.Color(246, 246, 246));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/v2icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1devhub.png"))); // NOI18N

        javax.swing.GroupLayout Barra1Layout = new javax.swing.GroupLayout(Barra1);
        Barra1.setLayout(Barra1Layout);
        Barra1Layout.setHorizontalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(7, 7, 7))
        );
        Barra1Layout.setVerticalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra1Layout.createSequentialGroup()
                .addGroup(Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Barra1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        txtOperacion.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_acActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        addNumber("/");
        
    }//GEN-LAST:event_divActionPerformed

    private void elActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elActionPerformed
        addNumber("^");
    }//GEN-LAST:event_elActionPerformed

    private void puntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntActionPerformed
        addNumber(".");
    }//GEN-LAST:event_puntActionPerformed

    private void entrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrActionPerformed
        addNumber("%");
    }//GEN-LAST:event_entrActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        addNumber("9");
    }//GEN-LAST:event_n9ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        addNumber("6");
    }//GEN-LAST:event_n6ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        addNumber("3");
    }//GEN-LAST:event_n3ActionPerformed

    private void igActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igActionPerformed
        JOptionPane.showMessageDialog(null, "Esta funcion será añadida próximamente");

    }//GEN-LAST:event_igActionPerformed

    private void porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porActionPerformed
        addNumber("*");
    }//GEN-LAST:event_porActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        addNumber("-");
    }//GEN-LAST:event_restActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        addNumber("+");
       
    }//GEN-LAST:event_sumActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        addNumber("7");
    }//GEN-LAST:event_n7ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        addNumber("4");
    }//GEN-LAST:event_n4ActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        addNumber("0");
    }//GEN-LAST:event_n0ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        addNumber("8");
    }//GEN-LAST:event_n8ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        addNumber("5");
    }//GEN-LAST:event_n5ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        addNumber("2");
    }//GEN-LAST:event_n2ActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        addNumber("1");
    }//GEN-LAST:event_n1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }
    public void addNumber (String digito){
        txtOperacion.setText(txtOperacion.getText()+digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra1;
    private javax.swing.JButton ac;
    private javax.swing.JButton div;
    private javax.swing.JButton el;
    private javax.swing.JButton entr;
    private javax.swing.JButton ig;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton por;
    private javax.swing.JButton punt;
    private javax.swing.JButton rest;
    private javax.swing.JButton sum;
    private javax.swing.JLabel txtOperacion;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
