/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import desplazable.Desface;
import javax.swing.ImageIcon;

/**
 *
 * @author Tijex
 */
public class proyectoFB extends javax.swing.JFrame {

    private String dato;
    
    Desface desplace;
    public proyectoFB() {
        
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/DevHuvbn.png")).getImage());
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        
        menu2.setVisible(false);
        menu3.setVisible(false);
        menu4.setVisible(false);
        menu5.setVisible(false);
        menu6.setVisible(false);
        menu7.setVisible(false);
        menu8.setVisible(false);
        
        derechaVU.setVisible(false);
        derechaVR.setVisible(false);
        derechaMa.setVisible(false);
        derechaPil.setVisible(false);
        derechaCola.setVisible(false);
        derechaList.setVisible(false);
        derechaCon.setVisible(false);
        izquierdaCola.setVisible(false);
        izquierdaPil.setVisible(false);
        izquierdaMa.setVisible(false);
        izquierdaVR.setVisible(false);
        izquierdaVU.setVisible(false);
        izquierdaCiclo1.setVisible(false);
        izquierdaCon.setVisible(false);
        
        Boton2.setVisible(false);
        Boton3.setVisible(false);
        Boton4.setVisible(false);
        Boton5.setVisible(false);
        Boton6.setVisible(false);
        Boton7.setVisible(false);
        Boton8.setVisible(false);
        
        this.setLocationRelativeTo(null);
        desplace = new Desface();
        
    }
    public void setDato(String dato){
        this.dato = dato;
        lbldato.setText(dato);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buscador = new javax.swing.JComboBox<>();
        lbldato = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Boton8 = new javax.swing.JLabel();
        Boton7 = new javax.swing.JLabel();
        Boton6 = new javax.swing.JLabel();
        Boton5 = new javax.swing.JLabel();
        Boton4 = new javax.swing.JLabel();
        Boton3 = new javax.swing.JLabel();
        Boton2 = new javax.swing.JLabel();
        Boton1 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        izquierdaCon = new javax.swing.JLabel();
        izquierdaCiclo1 = new javax.swing.JLabel();
        izquierdaVU = new javax.swing.JLabel();
        izquierdaVR = new javax.swing.JLabel();
        izquierdaMa = new javax.swing.JLabel();
        izquierdaPil = new javax.swing.JLabel();
        izquierdaCola = new javax.swing.JLabel();
        izquierdaList = new javax.swing.JLabel();
        derechaCon = new javax.swing.JLabel();
        derechaList = new javax.swing.JLabel();
        derechaCola = new javax.swing.JLabel();
        derechaPil = new javax.swing.JLabel();
        derechaMa = new javax.swing.JLabel();
        derechaVR = new javax.swing.JLabel();
        derechaVU = new javax.swing.JLabel();
        derechaCiclo1 = new javax.swing.JLabel();
        menu8 = new javax.swing.JLabel();
        menu7 = new javax.swing.JLabel();
        menu6 = new javax.swing.JLabel();
        menu5 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        menuP = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        Contrast = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra1.setBackground(new java.awt.Color(246, 246, 246));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/v2icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Proyecto Final- Programacion II - Ingenieria Industrial - Profesor Jorge Luis Escobar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1devhub.png"))); // NOI18N

        javax.swing.GroupLayout Barra1Layout = new javax.swing.GroupLayout(Barra1);
        Barra1.setLayout(Barra1Layout);
        Barra1Layout.setHorizontalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(7, 7, 7))
        );
        Barra1Layout.setVerticalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra1Layout.createSequentialGroup()
                .addGroup(Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 30));

        jPanel2.setBackground(new java.awt.Color(74, 74, 74));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Listas");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 50, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Colas");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 150, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Pilas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Matriz");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 150, -1));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Vectores Registros");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Vector Unidimensional");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Ciclos");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 94, -1));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Condicionales");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 94, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1bmenu_1.png"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2bmenu.png"))); // NOI18N
        jButton15.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2bmenu.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1condicionalv.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2condicional.png"))); // NOI18N
        jButton17.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2condicional.png"))); // NOI18N
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton17MouseExited(evt);
            }
        });
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, 40));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1ciclo.png"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2ciclo.png"))); // NOI18N
        jButton18.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2ciclo.png"))); // NOI18N
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton18MouseExited(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1vector.png"))); // NOI18N
        jButton19.setBorder(null);
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2vector.png"))); // NOI18N
        jButton19.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2vector.png"))); // NOI18N
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton19MouseExited(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 40));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1vectorR.png"))); // NOI18N
        jButton20.setBorder(null);
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2vectorR.png"))); // NOI18N
        jButton20.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2vectorR.png"))); // NOI18N
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton20MouseExited(evt);
            }
        });
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 40));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/matriz.png"))); // NOI18N
        jButton21.setBorder(null);
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2matriz.png"))); // NOI18N
        jButton21.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2matriz.png"))); // NOI18N
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton21MouseExited(evt);
            }
        });
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 40));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/piso.png"))); // NOI18N
        jButton22.setBorder(null);
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2piso.png"))); // NOI18N
        jButton22.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2piso.png"))); // NOI18N
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton22MouseExited(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 40));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cola.png"))); // NOI18N
        jButton23.setBorder(null);
        jButton23.setBorderPainted(false);
        jButton23.setContentAreaFilled(false);
        jButton23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton23.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2cola.png"))); // NOI18N
        jButton23.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2cola.png"))); // NOI18N
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton23MouseExited(evt);
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 40));

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1lista.png"))); // NOI18N
        jButton24.setBorder(null);
        jButton24.setBorderPainted(false);
        jButton24.setContentAreaFilled(false);
        jButton24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton24.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2listas.png"))); // NOI18N
        jButton24.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2listas.png"))); // NOI18N
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton24MouseExited(evt);
            }
        });
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1user.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2user.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2user.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, 40));

        buscador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buscar", "Condicional", "Ciclos", "Vector Unidimensional", "Vector Registros", "Matrices", "Pilas", "Colas", "Listas" }));
        buscador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });
        jPanel2.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 170, -1));

        lbldato.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        lbldato.setForeground(new java.awt.Color(204, 204, 204));
        lbldato.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbldato.setText("Usuario");
        lbldato.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(lbldato, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 40));

        jPanel1.setBackground(new java.awt.Color(58, 58, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton8MouseClicked(evt);
            }
        });
        jPanel1.add(Boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton7MouseClicked(evt);
            }
        });
        jPanel1.add(Boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton6MouseClicked(evt);
            }
        });
        jPanel1.add(Boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton5MouseClicked(evt);
            }
        });
        jPanel1.add(Boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton4MouseClicked(evt);
            }
        });
        jPanel1.add(Boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton3MouseClicked(evt);
            }
        });
        jPanel1.add(Boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton2MouseClicked(evt);
            }
        });
        jPanel1.add(Boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        Boton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton1MouseClicked(evt);
            }
        });
        jPanel1.add(Boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 100));

        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 100, 100));

        izquierdaCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaConMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaCiclo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaCiclo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaCiclo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaCiclo1MouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaCiclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaVU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaVU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaVU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaVUMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaVR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaVR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaVR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaVRMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaMa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaMaMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaPil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaPil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaPil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaPilMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaPil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaCola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaColaMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        izquierdaList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1izquierda.png"))); // NOI18N
        izquierdaList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        izquierdaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izquierdaListMouseClicked(evt);
            }
        });
        jPanel1.add(izquierdaList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        derechaCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaCon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaConMouseClicked(evt);
            }
        });
        jPanel1.add(derechaCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaListMouseClicked(evt);
            }
        });
        jPanel1.add(derechaList, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaCola.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaColaMouseClicked(evt);
            }
        });
        jPanel1.add(derechaCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaPil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaPil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaPil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaPilMouseClicked(evt);
            }
        });
        jPanel1.add(derechaPil, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaMa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaMaMouseClicked(evt);
            }
        });
        jPanel1.add(derechaMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaVR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaVR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaVR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaVRMouseClicked(evt);
            }
        });
        jPanel1.add(derechaVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaVU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaVU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaVU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaVUMouseClicked(evt);
            }
        });
        jPanel1.add(derechaVU, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        derechaCiclo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1derecha.png"))); // NOI18N
        derechaCiclo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        derechaCiclo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                derechaCiclo1MouseClicked(evt);
            }
        });
        jPanel1.add(derechaCiclo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, 40));

        menu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8menu.png"))); // NOI18N
        jPanel1.add(menu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/7menu.png"))); // NOI18N
        jPanel1.add(menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/6menu.png"))); // NOI18N
        jPanel1.add(menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/5menu.png"))); // NOI18N
        jPanel1.add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4menu.png"))); // NOI18N
        jPanel1.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/3menu.png"))); // NOI18N
        jPanel1.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2menu1.png"))); // NOI18N
        jPanel1.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1menu1.png"))); // NOI18N
        jPanel1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jButton10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(153, 153, 153));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1exit.png"))); // NOI18N
        jButton10.setText("Salir");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2exit.png"))); // NOI18N
        jButton10.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2exit.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 80, 50));

        menuP.setBackground(new java.awt.Color(88, 88, 88));

        jButton9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help.png"))); // NOI18N
        jButton9.setText("Ayuda ");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda2.png"))); // NOI18N
        jButton9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Multiply_32px.png"))); // NOI18N
        jButton14.setText("Calculadora ");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Calculator_32px.png"))); // NOI18N
        jButton14.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Calculator_32px.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1claro.png"))); // NOI18N
        jButton16.setText("Modo claro ");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2claro.png"))); // NOI18N
        jButton16.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2claro.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton25.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/credits.png"))); // NOI18N
        jButton25.setText("Créditos ");
        jButton25.setBorder(null);
        jButton25.setBorderPainted(false);
        jButton25.setContentAreaFilled(false);
        jButton25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton25.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2credits.png"))); // NOI18N
        jButton25.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2credits.png"))); // NOI18N
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1unicor.png"))); // NOI18N
        jButton26.setText("U. Córdoba ");
        jButton26.setBorder(null);
        jButton26.setBorderPainted(false);
        jButton26.setContentAreaFilled(false);
        jButton26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton26.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2unicor.png"))); // NOI18N
        jButton26.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2unicor.png"))); // NOI18N
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPLayout = new javax.swing.GroupLayout(menuP);
        menuP.setLayout(menuPLayout);
        menuPLayout.setHorizontalGroup(
            menuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(menuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton26)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        menuPLayout.setVerticalGroup(
            menuPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(menuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 510));

        Contrast.setBackground(new java.awt.Color(125, 125, 125));

        javax.swing.GroupLayout ContrastLayout = new javax.swing.GroupLayout(Contrast);
        Contrast.setLayout(ContrastLayout);
        ContrastLayout.setHorizontalGroup(
            ContrastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        ContrastLayout.setVerticalGroup(
            ContrastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(Contrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 220, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1050, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ayuda newframe = new ayuda();

        newframe.setVisible(true);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        login newframe = new login();
        
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"¿Seguro desea cerrar el programa?","Salir", dialog);
        if (result == 0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if(menuP.getX() == 0)
        {
        desplace.desplazarIzquierda(menuP, menuP.getX(), -180, 10, 10);
        } 
        else if(menuP.getX() == -180)
           {
               desplace.desplazarDerecha(menuP, menuP.getX(), 0, 10, 10);
           }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        ciclos newframe = new ciclos();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        condicionales newframe = new condicionales();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        vectorU newframe = new vectorU();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        vectorR newframe = new vectorR();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        matrices newframe = new matrices();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        pilas newframe = new pilas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        colas newframe = new colas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        listas newframe = new listas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseEntered
        jLabel1.setVisible(true);
    }//GEN-LAST:event_jButton18MouseEntered

    private void jButton18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseExited
        jLabel1.setVisible(false);
    }//GEN-LAST:event_jButton18MouseExited

    private void jButton17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_jButton17MouseEntered

    private void jButton17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseExited
        jLabel2.setVisible(false);
    }//GEN-LAST:event_jButton17MouseExited

    private void jButton19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseEntered
        jLabel3.setVisible(true);
    }//GEN-LAST:event_jButton19MouseEntered

    private void jButton19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseExited
        jLabel3.setVisible(false);
    }//GEN-LAST:event_jButton19MouseExited

    private void jButton20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseEntered
        jLabel4.setVisible(true);
    }//GEN-LAST:event_jButton20MouseEntered

    private void jButton20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseExited
        jLabel4.setVisible(false);
    }//GEN-LAST:event_jButton20MouseExited

    private void jButton21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseEntered
        jLabel7.setVisible(true);
    }//GEN-LAST:event_jButton21MouseEntered

    private void jButton21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseExited
        jLabel7.setVisible(false);
    }//GEN-LAST:event_jButton21MouseExited

    private void jButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseEntered
        jLabel8.setVisible(true);
    }//GEN-LAST:event_jButton22MouseEntered

    private void jButton22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseExited
        jLabel8.setVisible(false);
    }//GEN-LAST:event_jButton22MouseExited

    private void jButton23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseEntered
        jLabel9.setVisible(true);
    }//GEN-LAST:event_jButton23MouseEntered

    private void jButton23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseExited
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton23MouseExited

    private void jButton24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseEntered
        jLabel10.setVisible(true);
    }//GEN-LAST:event_jButton24MouseEntered

    private void jButton24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseExited
        jLabel10.setVisible(false);
    }//GEN-LAST:event_jButton24MouseExited

    private void derechaCiclo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaCiclo1MouseClicked
        menu2.setVisible(true);
        menu1.setVisible(false);
        derechaCiclo1.setVisible(false);
        derechaVU.setVisible(true);
        izquierdaList.setVisible(false);
        izquierdaCon.setVisible(true);
        Boton1.setVisible(false);
        Boton2.setVisible(true);
    }//GEN-LAST:event_derechaCiclo1MouseClicked

    private void izquierdaColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaColaMouseClicked
        menu7.setVisible(true);
        menu8.setVisible(false);
        izquierdaPil.setVisible(true);
        izquierdaCola.setVisible(false);
        derechaCon.setVisible(false);
        derechaList.setVisible(true);
        Boton7.setVisible(true);
        Boton8.setVisible(false);
    }//GEN-LAST:event_izquierdaColaMouseClicked

    private void derechaVUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaVUMouseClicked
        menu3.setVisible(true);
        menu2.setVisible(false);
        derechaVR.setVisible(true);
        derechaVU.setVisible(false);
        izquierdaCon.setVisible(false);
        izquierdaCiclo1.setVisible(true);
        Boton3.setVisible(true);
        Boton2.setVisible(false);
    }//GEN-LAST:event_derechaVUMouseClicked

    private void izquierdaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaListMouseClicked
        menu8.setVisible(true);
        menu1.setVisible(false);
        izquierdaCola.setVisible(true);
        izquierdaList.setVisible(false);
        derechaCiclo1.setVisible(false);
        derechaCon.setVisible(true);
        Boton8.setVisible(true);
        Boton1.setVisible(false);
    }//GEN-LAST:event_izquierdaListMouseClicked

    private void derechaVRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaVRMouseClicked
        menu4.setVisible(true);
        menu3.setVisible(false);
        derechaMa.setVisible(true);
        derechaVR.setVisible(false);
        izquierdaCiclo1.setVisible(false);
        izquierdaVU.setVisible(true);
        Boton4.setVisible(true);
        Boton3.setVisible(false);
    }//GEN-LAST:event_derechaVRMouseClicked

    private void derechaMaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaMaMouseClicked
        menu5.setVisible(true);
        menu4.setVisible(false);
        derechaPil.setVisible(true);
        derechaMa.setVisible(false);
        izquierdaVU.setVisible(false);
        izquierdaVR.setVisible(true);
        Boton5.setVisible(true);
        Boton4.setVisible(false);
    }//GEN-LAST:event_derechaMaMouseClicked

    private void derechaPilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaPilMouseClicked
        menu6.setVisible(true);
        menu5.setVisible(false);
        derechaCola.setVisible(true);
        derechaPil.setVisible(false);
        izquierdaVR.setVisible(false);
        izquierdaMa.setVisible(true);
        Boton6.setVisible(true);
        Boton5.setVisible(false);
    }//GEN-LAST:event_derechaPilMouseClicked

    private void derechaColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaColaMouseClicked
        menu7.setVisible(true);
        menu6.setVisible(false);
        derechaList.setVisible(true);
        derechaCola.setVisible(false);
        izquierdaMa.setVisible(false);
        izquierdaPil.setVisible(true);
        Boton7.setVisible(true);
        Boton6.setVisible(false);
    }//GEN-LAST:event_derechaColaMouseClicked

    private void derechaListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaListMouseClicked
        menu8.setVisible(true);
        menu7.setVisible(false);
        derechaCon.setVisible(true);
        derechaList.setVisible(false);
        izquierdaPil.setVisible(false);
        izquierdaCola.setVisible(true);
        Boton8.setVisible(true);
        Boton7.setVisible(false);
    }//GEN-LAST:event_derechaListMouseClicked

    private void derechaConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_derechaConMouseClicked
        menu1.setVisible(true);
        menu8.setVisible(false);
        derechaCiclo1.setVisible(true);
        derechaCon.setVisible(false);
        izquierdaCola.setVisible(false);
        izquierdaList.setVisible(true);
        Boton1.setVisible(true);
        Boton8.setVisible(false);
    }//GEN-LAST:event_derechaConMouseClicked

    private void izquierdaPilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaPilMouseClicked
        menu6.setVisible(true);
        menu7.setVisible(false);
        izquierdaMa.setVisible(true);
        izquierdaPil.setVisible(false);
        derechaList.setVisible(false);
        derechaCola.setVisible(true);
        Boton6.setVisible(true);
        Boton7.setVisible(false);
    }//GEN-LAST:event_izquierdaPilMouseClicked

    private void izquierdaMaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaMaMouseClicked
        menu5.setVisible(true);
        menu6.setVisible(false);
        izquierdaVR.setVisible(true);
        izquierdaMa.setVisible(false);
        derechaCola.setVisible(false);
        derechaPil.setVisible(true);
        Boton5.setVisible(true);
        Boton6.setVisible(false);
    }//GEN-LAST:event_izquierdaMaMouseClicked

    private void izquierdaVRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaVRMouseClicked
        menu4.setVisible(true);
        menu5.setVisible(false);
        izquierdaVU.setVisible(true);
        izquierdaVR.setVisible(false);
        derechaPil.setVisible(false);
        derechaMa.setVisible(true);
        Boton4.setVisible(true);
        Boton5.setVisible(false);
    }//GEN-LAST:event_izquierdaVRMouseClicked

    private void izquierdaVUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaVUMouseClicked
        menu3.setVisible(true);
        menu4.setVisible(false);
        izquierdaCiclo1.setVisible(true);
        izquierdaVU.setVisible(false);
        derechaMa.setVisible(false);
        derechaVR.setVisible(true);
        Boton3.setVisible(true);
        Boton4.setVisible(false);
    }//GEN-LAST:event_izquierdaVUMouseClicked

    private void izquierdaCiclo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaCiclo1MouseClicked
        menu2.setVisible(true);
        menu3.setVisible(false);
        izquierdaCon.setVisible(true);
        izquierdaCiclo1.setVisible(false);
        derechaVR.setVisible(false);
        derechaVU.setVisible(true);
        Boton2.setVisible(true);
        Boton3.setVisible(false);
    }//GEN-LAST:event_izquierdaCiclo1MouseClicked

    private void izquierdaConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izquierdaConMouseClicked
        menu1.setVisible(true);
        menu2.setVisible(false);
        izquierdaList.setVisible(true);
        izquierdaCon.setVisible(false);
        derechaVU.setVisible(false);
        derechaCiclo1.setVisible(true);
        Boton1.setVisible(true);
        Boton2.setVisible(false);
    }//GEN-LAST:event_izquierdaConMouseClicked

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        condicionales newframe = new condicionales();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton1MouseClicked

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        ciclos newframe = new ciclos();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton2MouseClicked

    private void Boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton3MouseClicked
        vectorU newframe = new vectorU();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton3MouseClicked

    private void Boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton4MouseClicked
        vectorR newframe = new vectorR();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton4MouseClicked

    private void Boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton5MouseClicked
        matrices newframe = new matrices();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton5MouseClicked

    private void Boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton6MouseClicked
        pilas newframe = new pilas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton6MouseClicked

    private void Boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton7MouseClicked
        colas newframe = new colas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton7MouseClicked

    private void Boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton8MouseClicked
        listas newframe = new listas();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_Boton8MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        calculadora newframe = new calculadora();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        proyectoF newframe = new proyectoF();
        
        newframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        creditos newframe = new creditos();
        
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cuentaB newframe = new cuentaB();

        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        String opcionSeleccionada = (String) buscador.getSelectedItem();

        if (opcionSeleccionada.equals("Condicional")){
            condicionales newframe = new condicionales();

            newframe.setVisible(true);
        }
        else if (opcionSeleccionada.equals("Ciclos")){
            ciclos newframe = new ciclos();

            newframe.setVisible(true);
        }
        else if (opcionSeleccionada.equals("Vector Unidimensional")){
            vectorU newframe = new vectorU();

            newframe.setVisible(true);
        }
        else if (opcionSeleccionada.equals("Vector Registros")){
            vectorR newframe = new vectorR();

            newframe.setVisible(true);
        }
        else if (opcionSeleccionada.equals("Matrices")){
            matrices newframe = new matrices();

            newframe.setVisible(true);

        }
        else if (opcionSeleccionada.equals("Pilas")){
            pilas newframe = new pilas();

            newframe.setVisible(true);

        }
        else if (opcionSeleccionada.equals("Colas")){
            colas newframe = new colas();

            newframe.setVisible(true);

        }
        else if (opcionSeleccionada.equals("Listas")){
            listas newframe = new listas();

            newframe.setVisible(true);
        }

    }//GEN-LAST:event_buscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proyectoFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proyectoFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proyectoFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proyectoFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proyectoFB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra1;
    private javax.swing.JLabel Boton1;
    private javax.swing.JLabel Boton2;
    private javax.swing.JLabel Boton3;
    private javax.swing.JLabel Boton4;
    private javax.swing.JLabel Boton5;
    private javax.swing.JLabel Boton6;
    private javax.swing.JLabel Boton7;
    private javax.swing.JLabel Boton8;
    private javax.swing.JPanel Contrast;
    private javax.swing.JComboBox<String> buscador;
    private javax.swing.JLabel derechaCiclo1;
    private javax.swing.JLabel derechaCola;
    private javax.swing.JLabel derechaCon;
    private javax.swing.JLabel derechaList;
    private javax.swing.JLabel derechaMa;
    private javax.swing.JLabel derechaPil;
    private javax.swing.JLabel derechaVR;
    private javax.swing.JLabel derechaVU;
    private javax.swing.JLabel izquierdaCiclo1;
    private javax.swing.JLabel izquierdaCola;
    private javax.swing.JLabel izquierdaCon;
    private javax.swing.JLabel izquierdaList;
    private javax.swing.JLabel izquierdaMa;
    private javax.swing.JLabel izquierdaPil;
    private javax.swing.JLabel izquierdaVR;
    private javax.swing.JLabel izquierdaVU;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbldato;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu4;
    private javax.swing.JLabel menu5;
    private javax.swing.JLabel menu6;
    private javax.swing.JLabel menu7;
    private javax.swing.JLabel menu8;
    private javax.swing.JPanel menuP;
    // End of variables declaration//GEN-END:variables
}
