/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tijex
 */
public class vectorR extends javax.swing.JFrame {
    vectorRC v=new vectorRC();
      int cont=0;
      int cont1=0,cont2=0;
    
    public vectorR() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/DevHuvbn.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spri = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        spar = new javax.swing.JTextField();
        Dato = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        simp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ver = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmed = new javax.swing.JTextField();
        cmedi = new javax.swing.JTextField();
        cdes = new javax.swing.JTextField();
        cmod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        veror = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jele = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Barra1 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        proim = new javax.swing.JTextField();
        propri = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ppar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pimp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setText("Vector Registros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 184, -1));

        spri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriActionPerformed(evt);
            }
        });
        getContentPane().add(spri, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 80, -1));

        jLabel20.setText("S.primos:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, -1));

        jButton5.setText("Mostrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));
        getContentPane().add(spar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, -1));
        getContentPane().add(Dato, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 70, -1));

        jLabel11.setText("S.pares:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 50, -1));

        jLabel3.setText("Dato a anadir:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(simp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 80, -1));

        jLabel4.setText("Mostrar Vector");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel12.setText("S.impares:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 60, 20));

        ver.setColumns(20);
        ver.setRows(5);
        jScrollPane1.setViewportView(ver);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 200));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 51, -1));

        jButton3.setText("Añadir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel5.setText("Operaciones requeridas :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        cmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmedActionPerformed(evt);
            }
        });
        getContentPane().add(cmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 70, -1));
        getContentPane().add(cmedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 80, -1));

        cdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdesActionPerformed(evt);
            }
        });
        getContentPane().add(cdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 80, -1));

        cmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmodActionPerformed(evt);
            }
        });
        getContentPane().add(cmod, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 70, -1));

        jLabel6.setText("Media:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel7.setText("Mediana:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel8.setText("Des. estandar:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel9.setText("Moda:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jButton7.setText("Calcular");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jButton8.setText("Limpiar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, -1));

        jLabel10.setText("Vector ordenado");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        veror.setColumns(20);
        veror.setRows(5);
        jScrollPane2.setViewportView(veror);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 200));

        jLabel2.setText("VECTROR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel21.setText("N°.de elementos:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeleActionPerformed(evt);
            }
        });
        getContentPane().add(jele, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));

        jButton6.setText("Promediar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jButton4.setText("Potenciar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, -1, -1));

        Barra1.setBackground(new java.awt.Color(246, 246, 246));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/v2icons8_Expand_Arrow_32px.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2icons8_Expand_Arrow_32px_1.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1devhub.png"))); // NOI18N

        javax.swing.GroupLayout Barra1Layout = new javax.swing.GroupLayout(Barra1);
        Barra1.setLayout(Barra1Layout);
        Barra1Layout.setHorizontalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Barra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 545, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(7, 7, 7))
        );
        Barra1Layout.setVerticalGroup(
            Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra1Layout.createSequentialGroup()
                .addGroup(Barra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Barra1Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jLabel19.setText("Teniendo en cuenta las condiciones establesidas");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, 20));
        jPanel1.add(proim, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 70, 30));
        jPanel1.add(propri, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 70, 30));

        jLabel18.setText("Pro.primos:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, 20));

        jLabel17.setText("Pro.impar:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, 20));

        jButton9.setText("¿Como funciona?");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel16.setText("Potencia a la 3");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel13.setText("P.pares:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));
        jPanel1.add(ppar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 70, -1));

        jLabel15.setText("Potencia a la 4");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jLabel14.setText("P.impares:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));
        jPanel1.add(pimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spriActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int aux;
        for (int i=0; i<v.getnump()-1; i++)
        {
            for (int j=i+1; j<v.getnump(); j++)
            {
                if(v.getnum(i)>v.getnum(j))
                {
                    aux = v.getnum(i);
                    v.setnum(i, v.getnum(j));
                    v.setnum(j, aux);
                }
            }
        }
        veror.setText("");
        int i;

        for(i=0; i<v.getnump();i++)
        {
            veror.append(""+v.getnum(i)+"\n");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        double t,c=0;
        t=Math.pow(cont2, 3);
        c=Math.pow(cont1, 4);
        ppar.setText(String.valueOf(t));
        pimp.setText(String.valueOf(c));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n=Integer.parseInt(jele.getText());
        v.setnump(n);
        v.crearVector();
        JOptionPane.showMessageDialog(null, "Tamaño Asignado");
        ver.setText("");

        Dato.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(cont<v.getnump())
        {
            int ele=Integer.parseInt(Dato.getText());
            v.setnum(cont, ele);
            ver.append(""+v.getnum(cont)+"\n");
            cont++;
        }
        else
        {
            ver.setText("No se puede añadir otro elemento");
        }
        Dato.setText("");
        Dato.grabFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmedActionPerformed

    private void cdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdesActionPerformed

    private void cmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmodActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int i;
        double pro = 0,con = 0;
        double t=0;
        for( i=0; i<v.getnump();i++)
        {
            if(v.getnum(i)>5 ){

                if(v.getnum(i)<15 ){
                    if(v.getnum(i)%2==1){
                        con=con+1;
                        pro=pro+v.getnum(i);
                        t=pro/con;
                    }
                }
            }
        }
        proim.setText(String.valueOf(t));

        double axu=0;
        double acum=0;
        int j;
        double c = 0;
        for(i=0;i<v.getnump();i++){
            if(v.getnum(i)>5 ){
                if(v.getnum(i)<13 ){
                    c=0;
                    for(j=1;j<=v.getnum(i);j++){
                        if((v.getnum(i)%j)==0){
                            c=c+1;
                        }
                    }
                    if(c<=2){

                        acum=acum+v.getnum(i);
                    }
                    axu=acum/c;
                }
            }
        }
        propri.setText(String.valueOf(axu));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        double des=0;
        int i;

        Map<Integer, Integer> frecuencias = new HashMap<>();

        for (i = 0; i <v.getnump() ; i++)
        {
            if (frecuencias.containsKey(v.num[i])) {
                frecuencias.put(v.num[i], frecuencias.get(v.num[i]) + 1);
            } else {
                frecuencias.put(v.num[i], 1);
            }

        }
        int mo = 0;
        int maxFrecuencia = 0;
        for (Map.Entry<Integer, Integer> entry : frecuencias.entrySet()) {
            if (entry.getValue() > maxFrecuencia) {
                mo = entry.getKey();
                maxFrecuencia = entry.getValue();
            }
        }
        cmod.setText(String.valueOf(mo));

        double m=0.0 ;
        int tamaño = 0;
        tamaño = v.getnump();
        if (tamaño % 2 == 0) {
            m= ((v.num[(tamaño / 2)-1 ] + v.num[(tamaño / 2)]) / 2);
        } else {
            m= v.num[((tamaño) / 2)];
        }
        cmedi.setText(String.valueOf(m));
        double prom,acum=0;

        for(i=0; i<v.getnump();i++)
        {
            acum=acum+v.getnum(i);
        }
        prom=acum/v.getnump();
        cmed.setText(String.valueOf(prom));

        double var = 0,sum=0;

        for(i=0; i<v.getnump();i++)
        {
            sum=(Math.pow(prom-v.getnum(i), 2));
            var=var+sum;

        }
        var=var/(v.getnump());
        des=Math.sqrt(var);

        cdes.setText(String.valueOf(des));

        for( i=0; i<v.getnump();i++)
        {
            if(v.getnum(i)%2==1){
                cont1=cont1+v.getnum(i);
            }
        }
        simp.setText(String.valueOf(cont1));
        for( i=0; i<v.getnump();i++)
        {
            if(v.getnum(i)%2==0){
                cont2=cont2+v.getnum(i);
            }
        }
        spar.setText(String.valueOf(cont2));
        int j;
        int cot1;
        for(i=0;i<v.getnump();i++){
            cot1=0;
            for(j=1;j<=v.getnum(i);j++){
                if((v.getnum(i)%j)==0){
                    cot1=cot1+1;
                }
            }
            if(cont1<=2){
                acum=acum+v.getnum(i);
            }
        }
        spri.setText(String.valueOf(acum));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jele.setText("");
        Dato.setText("");
        ver.setText("");
        veror.setText("");
        cmed.setText("");
        cmedi.setText("");
        cmod.setText("");
        propri.setText("");
        spar.setText("");
        simp.setText("");
        ppar.setText("");
        pimp.setText("");
        cdes.setText("");
        proim.setText("");
        Dato.grabFocus();
        cont=0;
        cont2=0;
        cont1=0;
        spri.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeleActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        tuto4 newframe = new tuto4();

        newframe.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vectorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vectorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vectorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vectorR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vectorR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra1;
    private javax.swing.JTextField Dato;
    private javax.swing.JTextField cdes;
    private javax.swing.JTextField cmed;
    private javax.swing.JTextField cmedi;
    private javax.swing.JTextField cmod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jele;
    private javax.swing.JTextField pimp;
    private javax.swing.JTextField ppar;
    private javax.swing.JTextField proim;
    private javax.swing.JTextField propri;
    private javax.swing.JTextField simp;
    private javax.swing.JTextField spar;
    private javax.swing.JTextField spri;
    private javax.swing.JTextArea ver;
    private javax.swing.JTextArea veror;
    // End of variables declaration//GEN-END:variables
}
